### ISSUE TITLE
NullPointer on startup

### ISSUE THREAD

**Issue by epsstan** [finos/legend-depot#195]
We seem to have a NPE on startup 

Clearly the role is not null. The previous line which uses the role does not throw.  
Is there a bug in the principal provider/injection ? 

```
72.25.0.1 - - [11/Feb/2023:16:34:00 +0000] "GET /depot-store/api/queue HTTP/1.1" 500 110 "http://localhost:6201/depot-store/api/swagger" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 11

127.0.0.1 - - [11/Feb/2023:16:34:03 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

INFO  [2023-02-11 16:34:04,301] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

INFO  [2023-02-11 16:34:04,303] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

ERROR [2023-02-11 16:34:07,328] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 5c5549426263a1a6

! java.lang.NullPointerException: null

! at org.finos.legend.depot.core.authorisation.services.BasicAuthorisationProvider.lambda$authorise$0(BasicAuthorisationProvider.java:63)

! at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)

! at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)

! at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)

! at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)

! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)

! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

! at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)

! at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)

! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

! at java.base/java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538)

! at org.finos.legend.depot.core.authorisation.services.BasicAuthorisationProvider.authorise(BasicAuthorisationProvider.java:63)

! at org.finos.legend.depot.core.authorisation.resources.BaseAuthorisedResource.validateUser(BaseAuthorisedResource.java:42)

! at org.finos.legend.depot.store.notifications.resources.NotificationsManagerResource.getAllEventsInQueue(NotificationsManagerResource.java:113)

! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

! at java.base/java.lang.reflect.Method.invoke(Method.java:566)

! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)

! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)

! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)

! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)

! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)

! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)

! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)

! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)

! at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)

! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at org.finos.legend.server.shared.bundles.HostnameHeaderBundle$Enricher.doFilter(HostnameHeaderBundle.java:62)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)

! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)

! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at org.finos.legend.server.pac4j.internal.UsernameFilter.doFilter(UsernameFilter.java:51)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at org.pac4j.j2e.filter.SecurityFilter.lambda$internalFilter$0(SecurityFilter.java:95)

! at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:159)

! at org.pac4j.j2e.filter.SecurityFilter.internalFilter(SecurityFilter.java:93)

! at org.pac4j.j2e.filter.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:81)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)

! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)

! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)

! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)

! at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:37)

! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)

! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)

! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)

! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

! at org.eclipse.jetty.server.Server.handle(Server.java:516)

! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)

! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)

! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)

! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)

! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)

! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)

! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)

! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)

! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)

! at java.base/java.lang.Thread.run(Thread.java:829)

172.25.0.1 - - [11/Feb/2023:16:34:07 +0000] "GET /depot-store/api/queue HTTP/1.1" 500 110 "http://localhost:6201/depot-store/api/swagger" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 3

127.0.0.1 - - [11/Feb/2023:16:34:08 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:34:13 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:34:18 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 4

127.0.0.1 - - [11/Feb/2023:16:34:24 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

INFO  [2023-02-11 16:34:24,122] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished storage-metrics 

INFO  [2023-02-11 16:34:24,305] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

INFO  [2023-02-11 16:34:24,310] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

127.0.0.1 - - [11/Feb/2023:16:34:29 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:34:34 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:34:39 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

INFO  [2023-02-11 16:34:44,300] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

127.0.0.1 - - [11/Feb/2023:16:34:44 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

INFO  [2023-02-11 16:34:44,304] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

127.0.0.1 - - [11/Feb/2023:16:34:49 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:34:54 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:34:59 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

INFO  [2023-02-11 16:35:04,299] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

INFO  [2023-02-11 16:35:04,301] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

127.0.0.1 - - [11/Feb/2023:16:35:04 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:09 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:35:14 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:19 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

INFO  [2023-02-11 16:35:24,123] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished storage-metrics 

INFO  [2023-02-11 16:35:24,298] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

INFO  [2023-02-11 16:35:24,301] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

127.0.0.1 - - [11/Feb/2023:16:35:24 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:29 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:34 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:39 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

INFO  [2023-02-11 16:35:44,298] org.finos.legend.depot.store.notifications.services.NotificationsQueueManager: waiting in queue 0

INFO  [2023-02-11 16:35:44,300] org.finos.legend.depot.schedules.services.SchedulesFactory: Finished queue-observer_1 

127.0.0.1 - - [11/Feb/2023:16:35:44 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2

127.0.0.1 - - [11/Feb/2023:16:35:49 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 3

127.0.0.1 - - [11/Feb/2023:16:35:55 +0000] "GET /depot-store/api/info HTTP/1.1" 200 218 "-" "curl/7.81.0" 2


```

**Comment by elopezcastro** [comment]
when do you see this? when you start the depot store server out of the box?
